### ISSUE TITLE
[Talk] From conception to creation, build a mobile app with the Orange Design System code libraries

### ISSUE THREAD

**Issue by B3nz01d** [Orange-OpenSource/ods-ios#204]
# Description
To support the Orange Dev and Test Days Conferences a talk needs to be prepared to support this subject.

# Subtasks
- [ ] articulate the content to be presented
- [ ] create the powerpoint slides
- [ ] create the script of the full presentation
- [ ] presentation rehearsals
- [ ] identify the detailed location of the presentation
- [ ] test the material configuration in the destination location
- [ ] record the presentation
