### ISSUE TITLE
[Talk] Android & iOS ODS: the new mobile code libraries (Support)

### ISSUE THREAD

**Issue by B3nz01d** [Orange-OpenSource/ods-ios#205]
# Description
To support the Orange Dev and Test Days Conferences a talk needs to be prepared to support this subject.
Support to the initial task lead here: https://github.com/Orange-OpenSource/ods-android/issues/250

# Subtasks
- [ ] articulate the content to be presented
- [ ] create the powerpoint slides
- [ ] create the script of the full presentation
- [ ] presentation rehearsals
- [ ] identify the detailed location of the presentation
- [ ] test the material configuration in the destination location
- [ ] record the presentation
