### ISSUE TITLE
Add accessiiblity statement in documentation, and open it through the app menu

### ISSUE THREAD

**Issue by pylapp** [Orange-OpenSource/ods-ios#786]
# Description

In the online documentation [(available at github.io)](https://orange-opensource.github.io/ods-ios/), add the last accessibility statement somewhere [(e.g. here)](https://github.com/Orange-OpenSource/ods-ios/tree/qualif/docs). No need to version this statement and keep several versions: one audit matches one version of the app but it is possible to have some versions of the app which were not audited. No interests in keeping several versions of the statement in the filetree : Git as a VCS will be enough.

# Tasks

- [x] Add in the documentation a new "accessiiblity-statement" folder
- [x] Place inside the elements
- [x] Update the app code to point to the HTML page

**Comment by pylapp** [comment]
Items to use attached
[a11y-orange-design-system.zip](https://github.com/Orange-OpenSource/ods-ios/files/14525765/a11y-orange-design-system.zip)

Linked to https://github.com/Orange-OpenSource/ods-ios/issues/764

**Comment by pylapp** [comment]
@pya35 I uploaded the resources you sent me in the documention folder. I changed also the URL to open in the app side.
However I still don't know how to test it ; I did not configure the Netlify process and I fear the online documentation will be updated only when releases are done.

@julien-deramond Do you have some ideas? Everyhing seems to be ok for me, but actually the URL in use (https://orange-opensource.github.io/ods-ios/accessibilityStatement/orange-design-system.html) points to the 404 page.
How to update the web documentation without making releases (if it is possible)?

**Comment by julien-deramond** [comment]
Locally, in your `qualif` branch it works well:
```
cd docs
bundle install
bundle exec jekyll serve -H 0.0.0.0 --trace --watch --force_polling --livereload --livereload-port 4002
# Then going to http://localhost:4000/ods-ios/accessibilityStatement/orange-design-system.html shows the page
```
When it's been merged, nothing was triggered to update the public documentation:
![Screenshot 2024-03-08 at 06 26 28](https://github.com/Orange-OpenSource/ods-ios/assets/17381666/a8d61281-54f9-4e3b-81c1-655b7e6907ee)

IMO this is kinda normal since you'd want your documentation to be public only either when you release, or each time you push to your `main` branch (IDK your current approach).

With your [release commit](https://github.com/Orange-OpenSource/ods-ios/commit/c9bbf12a310fb3ef649697a75989fe62283adeda) the other day on the _main_ branch, the update of the documentation happened:

![Screenshot 2024-03-08 at 06 29 42](https://github.com/Orange-OpenSource/ods-ios/assets/17381666/3389e45d-ef60-443f-8fe8-b43bfa2b0972)

IDK exactly how it's configured the project, but some commits on the _main_ branch launch the update of the documentation and others don't. We'd need to check that together. But the idea here would be for you to get this documentation modification (the corresponding commit of this issue) into your _main_ branch and retrigger if possible the process that updates the doc without releasing a new version of the lib.

**Comment by pylapp** [comment]
Thank you for all these details!
Documentation has been merged, and the evolution is available since the new [release v1.1.0](https://github.com/Orange-OpenSource/ods-ios/releases/tag/1.1.0).
More details in the dedicated announcement #790 :)

**Comment by pya35** [comment]
Thank you for the good job @pylapp
